# ------------------------------------------------------------------------------------------------------------------------
# Pipeline to build and deploy Azure Resources and Database
# See readme file for info about variable group "SQLDeployDemo"
# ------------------------------------------------------------------------------------------------------------------------
name: $(date:yyyy).$(date:MM).$(date:dd)$(rev:.r)
pool:
  vmImage: windows-latest # dacpac restore only runs on Windows...

# ------------------------------------------------------------------------------------------------------------------------
trigger:
  # since this repo has both AzDO and GHA pipelines, nothing is run automatically...
  - none
  # batch: true
  # branches:
  #   include:
  #     - main
  #   exclude:
  #     - '**/*.md'
  # paths:
  #   include:
  #     - 'src\sql.database/*'

# ----------------------------------------------------------------------------------------------------
parameters:
  - name: deployMultiStage
    displayName: Multi-Stage Deploy
    type: boolean
    default: false
  - name: runGHASScan
    displayName: Run GHAS Scan
    type: boolean
    default: false
  - name: runMSDevSecOpsScan
    displayName: Run MS DevSecOps Scan
    type: boolean
    default: false

# ----------------------------------------------------------------------------------------------------
variables:
  - group: SQLDeployDemo

# ----------------------------------------------------------------------------------------------------
stages:
- ${{ if eq(lower(parameters.deployMultiStage), 'false') }}:
  - template: pipes/infra-and-schema-pipe.yml
    parameters:
      environments: ['DEMO']
      appFolderName: 'src\sql.database'
      appSolutionName: 'sql.database'
      appProjectFolderName: 'src\sql.database\sql.database'
      appProjectName: 'sql.database'
      appProjectExtension: 'sqlproj'
      runMSDevSecOpsScan: ${{ parameters.runMSDevSecOpsScan }}
      runGHASScan: ${{ parameters.runGHASScan }}

- ${{ if eq(lower(parameters.deployMultiStage), 'true') }}:
  - template: pipes/infra-and-schema-pipe.yml
    parameters:
      environments: ['DEMO','QA']
      appFolderName: 'src\sql.database'
      appSolutionName: 'sql.database'
      appProjectFolderName: 'src\sql.database\sql.database'
      appProjectName: 'sql.database'
      appProjectExtension: 'sqlproj'
      runMSDevSecOpsScan: ${{ parameters.runMSDevSecOpsScan }}
      runGHASScan: ${{ parameters.runGHASScan }}
