# ------------------------------------------------------------------------------------------------------------------------
# Pipeline to deploy Azure Resources Only
# See readme file for info about variable group "SQLDeployDemo"
# ------------------------------------------------------------------------------------------------------------------------
name: $(date:yyyy).$(date:MM).$(date:dd)$(rev:.r)
pool:
  vmImage: windows-latest # dacpac restore only runs on Windows...

# ------------------------------------------------------------------------------------------------------------------------
trigger:
  # since this repo has both AzDO and GHA pipelines, nothing is run automatically...
  - none
  # batch: true
  # branches:
  #   include:
  #     - main
  # paths:
  #   include: 
  #     - '**/*.yml'
  #     - '**/*.yaml'
  #     - '**/*.bicep'

# ----------------------------------------------------------------------------------------------------
parameters:
  - name: deployMultiStage
    displayName: Multi-Stage Deploy
    type: boolean
    default: false
  - name: runDevSecOpsScan
    displayName: Run MS DevSecOps Scan
    type: boolean
    default: false
  # - name: runGHASScan
  #   displayName: Run GHAS Scan
  #   type: boolean
  #   default: false
  # - name: runPsRuleScan
  #   displayName: Run PSRule Bicep Scan
  #   type: boolean
  #   default: false

# ----------------------------------------------------------------------------------------------------
variables:
  - group: SQLDeployDemo

# ----------------------------------------------------------------------------------------------------
stages:
- ${{ if eq(lower(parameters.deployMultiStage), 'false') }}:
  - template: pipes/infra-only-pipe.yml
    parameters:
      environments: ['DEMO']
      runDevSecOpsScan: ${{ parameters.runDevSecOpsScan }}
      #runGHASScan: ${{ parameters.runGHASScan }}
      #runPsRuleScan: ${{ parameters.runPsRuleScan }}

- ${{ if eq(lower(parameters.deployMultiStage), 'true') }}:
  - template: pipes/infra-only-pipe.yml
    parameters:
      environments: ['DEMO','QA']
      runDevSecOpsScan: ${{ parameters.runDevSecOpsScan }}
      #runGHASScan: ${{ parameters.runGHASScan }}
      #runPsRuleScan: ${{ parameters.runPsRuleScan }}
