# ------------------------------------------------------------------------------------------------------------------------
# Pipeline to Run Security Scan
# ------------------------------------------------------------------------------------------------------------------------
name: $(date:yyyy).$(date:MM).$(date:dd)$(rev:.r)
pool:
  vmImage: windows-latest # dacpac restore only runs on Windows...

# ------------------------------------------------------------------------------------------------------------------------
schedules:
- cron: '0 0 * * *'
  displayName: Daily midnight build
  branches:
    include:
    - master

# ----------------------------------------------------------------------------------------------------
parameters:
  - name: runGHASScan
    displayName: Run GHAS Scan
    type: boolean
    default: true
  - name: runMSDevSecOpsScan
    displayName: Run MS DevSecOps Scan
    type: boolean
    default: false

# ----------------------------------------------------------------------------------------------------
stages:
- stage: ScanApplication
  displayName: Scan Application
  jobs:
  - template: pipes/templates/scan-code-template.yml
    parameters:
      environmentName: 'DEMO'
      appFolderName: 'src\sql.database'
      appSolutionName: 'sql.database'
      appProjectFolderName: 'src\sql.database\sql.database'
      appProjectExtension: 'sqlproj'
      runGHASScan: ${{ parameters.runGHASScan }}
      runMSDevSecOpsScan: ${{ parameters.runMSDevSecOpsScan }}
