# ----------------------------------------------------------------------------------------------------
# Template to deploy a SQL Dacpac File to a SQL Database
# ----------------------------------------------------------------------------------------------------
parameters: 
- name: environmentName
  default:  'DEMO'
- name: artifactName
  default: 'dacpac'
- name: appProjectName
  default: ''

# ------------------------------------------------------------------------------------------------------------------------
jobs:
- deployment: Deploy${{ parameters.environmentName }}Schema
  displayName: Initialize ${{ parameters.environmentName }} Deploy Schema
  environment: ${{ parameters.environmentName }}

- job: DeployDB${{ parameters.environmentName }}Schema
  displayName: Deploy ${{ parameters.environmentName }} Schema
  variables:
    - name: environmentNameUpper
      value: ${{ upper(parameters.environmentName) }}
    - name: environmentNameLower
      value: ${{ lower(parameters.environmentName) }}
    - name: sqlServerName
      value: $(sqlServerNamePrefix)${{ lower(parameters.environmentName) }}
    - name: fqdnServerName
      value: $(sqlServerName).database.windows.net

  steps:
  - task: DownloadBuildArtifacts@0
    displayName: 'Download Build Artifacts'
    inputs:
      buildType: 'current'
      downloadType: 'single'
      artifactName: '${{ parameters.artifactName }}'
      downloadPath: '$(System.ArtifactsDirectory)'

  - task: CmdLine@2
    displayName: 'Display Variables and Files'
    inputs:
      script: |
        echo "serviceConnectionName=$(serviceConnectionName)"
        echo "environmentNameUpper=$(environmentNameUpper)"
        echo "environmentNameLower=$(environmentNameLower)"
        echo "artifactName=${{ parameters.artifactName }}"
        echo "sqlServerNamePrefix=$(sqlServerNamePrefix)"
        echo "sqlServerName=$(sqlServerName)"
        echo "fqdnServerName=$(fqdnServerName)"
        echo "sqlDatabaseName=$(sqlDatabaseName)"
        echo "sqlAdminUser=$(sqlAdminUser)"
        echo "sqlAdminPassword=$(sqlAdminPassword)"
        echo "DacpacFileLocation=$$(System.ArtifactsDirectory)\${{ parameters.artifactName }}\*.dacpac"
        echo "Directory of Artifacts Directory: $(System.ArtifactsDirectory)"
        dir $(System.ArtifactsDirectory) /s
    continueOnError: true

  - task: SqlAzureDacpacDeployment@1
    displayName: 'Deploy Azure SQL DB'
    inputs:
      azureSubscription: '$(serviceConnectionName)'
      ServerName: '$(fqdnServerName)'
      DatabaseName: '$(sqlDatabaseName)'
      DacpacFile: '$(System.ArtifactsDirectory)\${{ parameters.artifactName }}\${{ parameters.appProjectName }}.dacpac'
      AuthenticationType: 'servicePrincipal' # 'server' | 'aadAuthenticationPassword' | 'aadAuthenticationIntegrated' | 'connectionString' | 'servicePrincipal'.  Default: server
      #AuthenticationType: 'server' # 'server' | 'aadAuthenticationPassword' | 'aadAuthenticationIntegrated' | 'connectionString' | 'servicePrincipal'.  Default: server
      # SqlUsername: '$(sqlAdminUser)'
      # SqlPassword: '$(sqlAdminPassword)'
      DeleteFirewallRule: false
      
      # Logins: (try this to get a token for the service principal)
      #  https://erikej.github.io/sqlserver/2021/02/01/azure-sql-advanced-deployment-part4.html

      # There are other possible actions that could be triggered:
      #   DeploymentAction: 'Publish' # 'Publish' | 'Extract' | 'Export' | 'Import' | 'Script' | 'DriftReport' | 'DeployReport'. Required when TaskNameSelector = DacpacTask. Action. Default: Publish.
      #   See: https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/sql-azure-dacpac-deployment-v1?view=azure-pipelines
      #        https://learn.microsoft.com/en-us/sql/tools/sqlpackage/sqlpackage?view=sql-server-ver15

      # If you want to drop tables not in the source you need to specify the parameter DropObjectsNotInSource=true
      # See:
      #   https://learn.microsoft.com/en-us/archive/blogs/ssdt/new-advanced-publish-options-to-specify-object-types-to-exclude-or-not-drop
      #   https://learn.microsoft.com/en-us/answers/questions/811899/sqlpackage-does-not-delete-the-tables-from-target
      #   https://dev.to/dealeron/dropping-objects-with-ssdt-33g2
      # NOTE: I can't get this to work right...!   (only valid with certain DeploymentActions...?)
      #   AdditionalArguments: DropObjectsNotInSource=true
      #   AdditionalArguments: # string. Optional. Use when TaskNameSelector/DeployType = DacpacTask || DeploymentAction = Extract || DeploymentAction = Export || DeploymentAction = Import || DeploymentAction = Script || DeploymentAction = DeployReport || DeploymentAction = DriftReport. Additional SqlPackage.exe Arguments. 
      #   DeployType: 'DacpacTask' # 'DacpacTask' | 'SqlTask' | 'InlineSqlTask'. Alias: TaskNameSelector. Required. Deploy type. Default: DacpacTask.
    
